# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ae3b25c130b7fecf8a0a927df9d94c1a"
name = "67-qr-code"
handle = "67-qr-code"
application_url = "https://macromedia-gdp-attend-plains.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "suelenalves.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://macromedia-gdp-attend-plains.trycloudflare.com/auth/callback",
  "https://macromedia-gdp-attend-plains.trycloudflare.com/auth/shopify/callback",
  "https://macromedia-gdp-attend-plains.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
